<?php

/**
 * Operational root for file operations
 */
define('SITE_ROOT','./sites/');


/**
 * Implements hook_node_view_alter
 */
function ucsiterequest_node_view_alter(&$build) {
  // Deny access to account owners to view nodes that do not belong to them
  global $user; 
  $roles = $user->roles;
  $is_accounts_admin = (in_array('accounts administrator', $roles) || in_array('administrator', $roles)) ? true : false;
  $is_account_owner = (in_array('account owner', $roles) && !$is_accounts_admin) ? true : false;

  if ($is_account_owner && $build['#bundle'] == 'ucsiterequestform' && $build['#node']->uid != $user->uid) {
    drupal_access_denied();
    module_invoke_all('exit');
    exit();
  }

  // Show only billing information for account owners
  if ($is_account_owner) {
    // First, disable access to all fields
    foreach ($build as $build_element_name => $build_element) {
      if (substr($build_element_name, 0, 6) == 'field_') {
        $build[$build_element_name]['#access'] = 0;
      }
    }

    // Now, selectively give access to certain fields
    $build['field_site_owner_name']['#access'] = 1;
    $build['field_cnet']['#access'] = 1;
    $build['field_billing_contact_name']['#access'] = 1;
    $build['field_billing_contact_cnet']['#access'] = 1;
    $build['field_billing_fas_number']['#access'] = 1;
  }
}

/**
 * Implements hook_form_alter().
 *
 * Prevents the following fields from being rendered to anonymous users:
 * node reference = site_request_node_form
 * type site_request
 * status (String, 1 characters ) 0/1
 * - field_database_name
 * - field_dbusername
 * - field_dbpassword
 * - field_approved
 */
function ucsiterequest_form_alter(&$form, $form_state, $form_id) {
  global $user; 
  global $base_url;
  $roles = $user->roles;
  set_ucsiterequest_variables();
  /* if anonymous user hide database info and approve check box */
  $anonymous = ($user->uid == 0 && $form_id == 'ucsiterequestform_node_form') ? true : false;
  $is_site_request = ($form_id == 'ucsiterequestform_node_form') ? true : false;
  $is_admin = ( in_array('administrator',$roles) || in_array('site owner',$roles) || in_array('accounts administrator',$roles) && $is_site_request ) ? true : false;
  $is_account_owner = in_array('account owner', $roles) ? true : false;
  $view = views_get_current_view();

  /* Hide all unused fields */
  $form['field_approved']['#access'] = 0;
  $form['field_add_site_name']['#access'] = 0;
  $form['field_siterequest_dbrequest']['#access'] = 0;
  $form['field_rejected']['#access'] = 0;
  $form['field_database_name']['#access'] = 0;
  $form['field_dbusername']['#access'] = 0;
  $form['field_dbpassword']['#access'] = 0;
  $form['field_dbhost']['#access'] = 0;
  $form['field_dbport']['#access'] = 0;
  $form['field_password']['#access'] = 0;
  $form['field_username']['#access'] = 0;
  $form['field_siteowner_email']['#access'] = 0;

  if ( $anonymous ) {
  	drupal_set_title('Request a UChicago Site'); 
  	$form['field_add_site_name']['#access'] = 0;
  	$form['field_rejected']['#access'] = 0;
  	$form['field_siterequest_dbrequest']['#access'] = 0;
  	$form['field_password']['#access'] = 0;
  	$form['field_username']['#access'] = 0;
  	$form['field_siteowner_email']['#access'] = 0;
  	$form['field_install_complete']['#access'] = 0;
    $form['field_billing_annual_rate']['#access'] = 0;
    $form['field_billing_client_group']['#access'] = 0;
    $form['field_status_launch']['#access'] = 0;
    $form['field_status_preferred_vhost']['#access'] = 0;
    $form['field_status_aliases']['#access'] = 0;
    $form['field_status_url_reserved']['#access'] = 0;
    $form['field_status_create_date']['#access'] = 0;
    $form['field_status_termination_date']['#access'] = 0;
    $form['field_status_notes']['#access'] = 0;

  	$form['actions']['submit']['#value'] = 'Submit';
  	/* redirect */
  	$form['actions']['submit']['#submit'][] = 'ucsiterequest_submit_handler';
	/* if admin user */
  } elseif ($is_admin && is_null($view) && $is_site_request) {

    /* Removed required property when in edit mode.
     * Some of these records were imported from legacy data and are incomplete.
     */
    $form['field_email'][$form['language']['#value']][0]['email']['#required'] = 0;
    $form['field_name'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_department'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_site_owner_name'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_cnet'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_site_owner_affiliation'][$form['language']['#value']]['#required'] = 0;
    $form['field_current_site'][$form['language']['#value']]['#required'] = 0;
    $form['field_site_description'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_billing_contact_cnet'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_billing_contact_name'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_billing_fas_number'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_site_is_faculty'][$form['language']['#value']]['#required'] = 0;
    $form['field_site_owner_department'][$form['language']['#value']][0]['value']['#required'] = 0;
    $form['field_site_owner_division'][$form['language']['#value']][0]['value']['#required'] = 0;
    /* End removal of required property. */

  	$node = $form_state['node']; 
  	if( $node->field_install_complete[$node->language][0]['value'] == 1 ){
  		$view_site_link = variable_get('site_environment') == 'prod' ? variable_get('new_sub_domain').'.sites.uchicago.edu' : variable_get('vhost') ;
  		$form['html_markup'] = array('#markup' => t('<h4><a href="https://'.$view_site_link.'" target="_blank" style="padding: 10px; margin-top:10px; border:1px solid #ccc; background-color: #eee;">View Site</a></h4>'));
  		$form['field_dbpassword']['#access'] = 0;
  	}
  	$form['#attributes'] = array('enctype' => "multipart/form-data");
   

    // Never allow publishing
    if ($form['actions']['submit']['#value'] == 'Publish') {
      $form['actions']['submit']['#access'] = 0;
    }

  /* if account owner */
  } elseif ($is_account_owner && is_null($view) && $is_site_request) {

    // Never allow publishing
    $form['actions']['submit']['#access'] = 0;

    // Disable access to the title
    $form['title']['#access'] = 0;

    // First, disable access to all fields
    foreach ($form as $form_element_name => $form_element) {
      if (substr($form_element_name, 0, 6) == 'field_') {
        $form[$form_element_name]['#access'] = 0;
      }
    }

    // Now, selectively give access to certain fields
    unset ($form['#groups']['group_siterequest_info']->format_settings['instance_settings']['description']);
    $form['field_site_owner_name']['#access'] = 1;
    $form['field_cnet']['#access'] = 1;
    $form['field_billing_contact_name']['#access'] = 1;
    $form['field_billing_contact_cnet']['#access'] = 1;
    $form['field_billing_fas_number']['#access'] = 1;

  }
  /*
   * ucsiterequest.view.inc sets this to true when the view is loaded
   * */
  variable_set('is_view', false);
}

/**
 * Implementation of hook_views_api().
 */
function ucsiterequest_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'ucsiterequest'),
  );
}

/**
 * Implements node_form_submit().
 */
function ucsiterequest_submit_handler($form, &$form_state) {
 	$form_state['redirect'] = 'site-request-confirm';
}

/**
*Possibly not used
*/

function set_ucsiterequest_variables(){
	global $base_url;
	global $user;
	$parts = parse_url($base_url);
	$arr = explode(".", $parts['host'] );
	if( isset($user->mail) )
	{
		variable_set('from_email' , $user->mail );
	}
	if (preg_match("/^sitesdev[0-9]*/", $arr[0] )) {
	   //set dev variables
	    variable_set('site_environment' , 'dev');
		variable_set('files_root', 'sites/sitesdev.uchicago.edu/files');
		variable_set('to_email' , $user->mail );
	    variable_set('cc_email' , $user->mail );
	} elseif( $arr[1] == "sites") {
	    //set prod variables
	    variable_set('site_environment' , 'prod');
	    variable_set('files_root', 'sites/base.sites.uchicago.edu/files');
		variable_set('to_email' ,'seamysql@lists.uchicago.edu');
		variable_set('cc_email' , 'sites-help@lists.uchicago.edu');
	}
}